apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: ladbhavesh1/testapp:latest
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: testapp-service
  namespace: demo
spec:
  clusterIP: 172.30.120.253
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 80
  selector:
    app: testapp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}