apiVersion: v1
kind: Service
metadata:
  name: testapp-service
  namespace: demo
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 80
  selector:
    app: testapp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}